### ISSUE TITLE
Support for cargo-hakari with cargo-udeps

### ISSUE THREAD

**Issue by tzilist** [facebookincubator/cargo-guppy#595]
Right now, cargo-hakari generates an immense amount of failures since none of the dependencies are used within the actual crate. It would be nice if there was an ability to automatically generate an ignored section like so:

```toml
### BEGIN HAKARI SECTION
[dependencies]
a = { version = "1.0" }
b = { version = "1.0}

[package.metadata.cargo-udeps.ignore]
normal = ["a", "b"]
### END HAKARI SECTION
```

Or something along these lines.

Thank you!

**Comment by sunshowers** [comment]
Thanks for the report! Could you point me to the format expected by cargo-udeps?

**Comment by tzilist** [comment]
@sunshowers I believe this is what you are lookin' for

https://github.com/est31/cargo-udeps#ignoring-some-of-the-dependencies

Let me know if you need anything else, and thanks again!

**Comment by sunshowers** [comment]
Thanks for the link! I'm going to try and get this done some time next week.

Notes:

This should be gated behind an optional config to maintain BC. I think it should look like:
```toml
[extras]
cargo-udeps-ignore = "1"
```

The "1" means format version 1. If the format changes in the future, the output can change as well.
