### ISSUE TITLE
Fix for inactive, optional dependencies in guppy 0.13

### ISSUE THREAD

**Issue by sunshowers** [facebookincubator/cargo-guppy#596]
This issue tracks the Cargo build simulation fix for inactive, optional dependencies in guppy 0.13 (commit e03f119cbb0ca5a59675ae851421f32b5ce18552).

More about this:
```toml
[package]
resolver = "2"
name = "main"

[target.'cfg(unix)'.dependencies]
dep = { version = "...", optional = true }

[features]
feat = ["dep/feat"]
```

Previously, the feature `main/feat` -> `main/dep` was activated unconditionally. This did not match Cargo's behavior, which only activated `main/feat` -> `main/dep` if `dep` was already active.

With guppy 0.13, guppy now matches Cargo's behavior.

This also causes a minor behavior change to hakari (#586).
